# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

#steps:
#- task: UseDotNet@2
#  displayName: 'Install .NET Core SDK'
#  inputs:
#    version: 5.0.x
#- task: NodeTool@0
#  inputs:
#    versionSpec: '10.x'
#  displayName: 'Install Node.js'
#- script: |
#    cd src/socket.io-server-v2
#    npm install
#    npm start & cd ../socket.io-server-v3
#    npm install
#    npm start & cd ../socket.io-server-v4
#    npm install
#    npm start & dotnet test ../SocketIOClient.Test

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
- script: |
    cd src
    dotnet test SocketIOClient.UnitTest